pages:
  image: alpine:latest
  script:
    - apk add make python3 py3-pip git
    - make specs
    - mv site public
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
