variables:
  GIT_DEPTH: 0

pages:
  image: alpine:latest
  script:
    - apk add make python3 py3-pip git tzdata
    - make specs
    - mv site public
  pages: true
  artifacts:
    paths:
      - public
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
